"""empty message

Revision ID: 144cb4a84248
Revises: 86b1557d5af5
Create Date: 2023-06-04 16:29:39.302816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144cb4a84248'
down_revision = '86b1557d5af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserv_1_starttime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserv_1_endtime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserv_2_starttime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserv_2_endtime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserv_3_starttime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reserv_3_endtime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reserv_3_endtime')
        batch_op.drop_column('reserv_3_starttime')
        batch_op.drop_column('reserv_2_endtime')
        batch_op.drop_column('reserv_2_starttime')
        batch_op.drop_column('reserv_1_endtime')
        batch_op.drop_column('reserv_1_starttime')

    # ### end Alembic commands ###
