"""empty message

Revision ID: 2c12f89e541a
Revises: 1bb29e89e679
Create Date: 2023-06-04 17:27:30.707196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c12f89e541a'
down_revision = '1bb29e89e679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserv_1_seat', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reserv_2_seat', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reserv_3_seat', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reserv_3_seat')
        batch_op.drop_column('reserv_2_seat')
        batch_op.drop_column('reserv_1_seat')

    # ### end Alembic commands ###
