"""empty message

Revision ID: cccb95c2cc5f
Revises: 1faa8813be13
Create Date: 2023-05-29 02:25:07.708393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccb95c2cc5f'
down_revision = '1faa8813be13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vio_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('susp_stat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('susp_stat')
        batch_op.drop_column('vio_count')

    # ### end Alembic commands ###
