"""empty message

Revision ID: da2ef0ee9fef
Revises: f0f6cfa11f52
Create Date: 2023-05-29 22:29:55.039852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2ef0ee9fef'
down_revision = 'f0f6cfa11f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_stat', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t__user', schema=None) as batch_op:
        batch_op.drop_column('login_stat')

    # ### end Alembic commands ###
